#! /bin/sh

# Autostart
feh --bg-scale ~/.config/wallpapers/black-mountian.jpg

bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc configuration

bspc config border_width	2 
bspc config window_gap		5

bspc config split_ratio		1
bspc config borderless_monocle	true
bspc config gapless_monocle	true



sxhkd & urxvt & urxvtd &

bash $HOME/.config/bar/lemonbar/lemonbar 


