#!/bin/bash

cd $(dirname -- $0)

. ./common

while read -r line; do
  case $line in 
        WIFI*)
          wifi_name="${line#????}"
          ;;
        DATE*)
          datetime="${line#????}"       
          ;;
        BATT*)
          battery="${line#????}"
          ;;
        BSPC*)
          desktop="${line#????}"
          ;;
        KUBE*)
          kube="${line#????}"
          ;;
        VPN*)
          vpn="${line#???}"
          ;;
        LANG*)
          layout="${line#????}"
          ;;
        *) ;;
  esac

  echo -e "%{l}${desktop} %{c} ${vpn} | ${kube} %{r} ${wifi_name}  ${battery}  %{U${color_hl1}}%{+u}${layout}%{-u}%{U-}  ${datetime} "
done
